name: Build artifacts
on: push
  # push:
  #   branches: main

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  iso:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        nix_path: nixpkgs=channel:nixos-unstable

    - uses: cachix/cachix-action@v14
      with:
        name: feltnerm
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build `monke` ISO
      run: nix build .#nixosConfigurations.monke.config.formats.iso
